insert into `college`(`name`) value('计算机工程与科学学院');
insert into `college`(`name`) value('理学院');
insert into `college`(`name`) value('钱伟长学院');
insert into `college`(`name`) value('材料科学与工程学院');
insert into `college`(`name`) value('通信与信息工程学院');
insert into `college`(`name`) value('经济学院');
insert into `college`(`name`) value('管理学院');
insert into `college`(`name`) value('文学院');
insert into `college`(`name`) value('法学院');